//! Recovery protocol — formal types, prompt composition, and protocol assembly.
//!
//! This module is the single authority for recovery semantics (Constitution §5).
//! Route handlers import from here; they never define recovery types inline.

use serde::{Deserialize, Serialize};

use crate::runtime_control::{
    ExecutionKind, ExecutionStatus, SessionExecutionNode, SessionExecutionTopology,
};

// ---------------------------------------------------------------------------
// Public protocol types
// ---------------------------------------------------------------------------

/// Overall status of a session's recovery protocol.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RecoveryProtocolStatus {
    /// Active executions are still running.
    Running,
    /// Pending questions must be answered before recovery can proceed.
    AwaitingUser,
    /// Recovery actions are available for selection.
    Recoverable,
    /// No recovery target was inferred.
    Idle,
}

/// Kind of recovery action the user can invoke.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RecoveryActionKind {
    AbortRun,
    AbortStage,
    Retry,
    Resume,
    PartialReplay,
    RestartStage,
    RestartSubtask,
}

/// Checkpoint information attached to a recoverable boundary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecoveryCheckpointInfo {
    pub id: String,
    pub kind: String,
    pub label: String,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduler_profile: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stage: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stage_index: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stage_total: Option<u32>,
}

/// A single recovery action that the protocol currently permits.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecoveryActionInfo {
    pub kind: RecoveryActionKind,
    pub label: String,
    pub description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target_kind: Option<String>,
}

/// Full recovery protocol snapshot for a session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionRecoveryProtocol {
    pub session_id: String,
    pub status: RecoveryProtocolStatus,
    pub active_execution_count: usize,
    pub pending_question_count: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_user_prompt: Option<String>,
    #[serde(default)]
    pub actions: Vec<RecoveryActionInfo>,
    #[serde(default)]
    pub checkpoints: Vec<RecoveryCheckpointInfo>,
}

/// Incoming request to execute a recovery action.
#[derive(Debug, Deserialize)]
pub struct ExecuteRecoveryRequest {
    pub action: RecoveryActionKind,
    #[serde(default)]
    pub target_id: Option<String>,
}

/// Internal context attached to a prompt that was generated by a recovery action.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub(crate) struct RecoveryExecutionContext {
    pub action: Option<RecoveryActionKind>,
    pub target_id: Option<String>,
    pub target_kind: Option<String>,
    pub target_label: Option<String>,
}

// ---------------------------------------------------------------------------
// Internal recovery target types
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
pub(crate) struct StageRecoveryTarget {
    pub checkpoint: RecoveryCheckpointInfo,
    pub body: String,
}

#[derive(Debug, Clone)]
pub(crate) struct SubtaskRecoveryTarget {
    pub checkpoint: RecoveryCheckpointInfo,
    pub description: String,
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn short_recovery_text(text: &str, max_chars: usize) -> Option<String> {
    let clean = text.trim();
    if clean.is_empty() {
        return None;
    }
    let mut out = String::new();
    for (count, ch) in clean.chars().enumerate() {
        if count >= max_chars {
            out.push('…');
            break;
        }
        out.push(ch);
    }
    Some(out)
}

/// Extract the text visible to the user from an assistant message.
///
/// Delegates to `crate::routes::stream::assistant_visible_text` when called
/// from the route layer. Here we accept a pre-extracted body string to keep
/// this module independent of the session message internals.
fn assistant_visible_text_from_message(message: &rocode_session::SessionMessage) -> String {
    let mut out = String::new();
    for part in &message.parts {
        if let rocode_session::PartType::Text { text, ignored, .. } = &part.part_type {
            if ignored.unwrap_or(false) {
                continue;
            }
            out.push_str(text);
        }
    }
    out
}

pub(crate) fn latest_user_prompt(session: &rocode_session::Session) -> Option<String> {
    session.messages.iter().rev().find_map(|message| {
        if !matches!(message.role, rocode_session::MessageRole::User) {
            return None;
        }

        #[derive(Debug, Default, serde::Deserialize)]
        struct UserPromptMetadataWire {
            #[serde(
                default,
                deserialize_with = "rocode_types::deserialize_opt_string_preserve"
            )]
            resolved_user_prompt: Option<String>,
        }

        let meta: UserPromptMetadataWire = rocode_types::parse_map_lossy(&message.metadata);

        meta.resolved_user_prompt
            .as_deref()
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .map(ToString::to_string)
            .or_else(|| {
                let text = message.get_text().trim().to_string();
                if text.is_empty() {
                    None
                } else {
                    Some(text)
                }
            })
    })
}

fn latest_assistant_finish(session: &rocode_session::Session) -> Option<String> {
    session
        .messages
        .iter()
        .rev()
        .find(|message| matches!(message.role, rocode_session::MessageRole::Assistant))
        .and_then(|message| message.finish.clone())
}

// ---------------------------------------------------------------------------
// Target collection
// ---------------------------------------------------------------------------

pub(crate) fn collect_stage_recovery_targets(
    session: &rocode_session::Session,
) -> Vec<StageRecoveryTarget> {
    session
        .messages
        .iter()
        .rev()
        .filter_map(|message| {
            #[derive(Debug, Default, serde::Deserialize)]
            struct StageRecoveryMetadataWire {
                #[serde(
                    default,
                    deserialize_with = "rocode_types::deserialize_opt_string_lossy"
                )]
                scheduler_stage: Option<String>,
                #[serde(
                    default,
                    deserialize_with = "rocode_types::deserialize_opt_string_lossy"
                )]
                resolved_scheduler_profile: Option<String>,
                #[serde(
                    default,
                    deserialize_with = "rocode_types::deserialize_opt_string_lossy"
                )]
                scheduler_profile: Option<String>,
                #[serde(
                    default,
                    deserialize_with = "rocode_types::deserialize_opt_string_lossy"
                )]
                scheduler_stage_status: Option<String>,
                #[serde(
                    default,
                    deserialize_with = "rocode_types::deserialize_opt_string_lossy"
                )]
                scheduler_stage_title: Option<String>,
                #[serde(
                    default,
                    deserialize_with = "rocode_types::deserialize_opt_string_lossy"
                )]
                scheduler_stage_focus: Option<String>,
                #[serde(
                    default,
                    deserialize_with = "rocode_types::deserialize_opt_u64_lossy"
                )]
                scheduler_stage_index: Option<u64>,
                #[serde(
                    default,
                    deserialize_with = "rocode_types::deserialize_opt_u64_lossy"
                )]
                scheduler_stage_total: Option<u64>,
            }

            let meta: StageRecoveryMetadataWire = rocode_types::parse_map_lossy(&message.metadata);
            let stage = meta.scheduler_stage?;
            let profile = meta.resolved_scheduler_profile.or(meta.scheduler_profile);
            let status = meta
                .scheduler_stage_status
                .unwrap_or_else(|| "done".to_string());
            let label = meta
                .scheduler_stage_title
                .or_else(|| meta.scheduler_stage_focus.map(|focus| format!("{stage} · {focus}")))
                .unwrap_or_else(|| stage.clone());
            let body = assistant_visible_text_from_message(message);
            Some(StageRecoveryTarget {
                checkpoint: RecoveryCheckpointInfo {
                    id: message.id.clone(),
                    kind: "stage".to_string(),
                    label,
                    status,
                    summary: short_recovery_text(&body, 240),
                    scheduler_profile: profile,
                    stage: Some(stage),
                    stage_index: meta.scheduler_stage_index.map(|value| value as u32),
                    stage_total: meta.scheduler_stage_total.map(|value| value as u32),
                },
                body,
            })
        })
        .collect()
}

pub(crate) fn collect_subtask_recovery_targets(
    session: &rocode_session::Session,
) -> Vec<SubtaskRecoveryTarget> {
    let mut targets = Vec::new();
    for message in session.messages.iter().rev() {
        if !matches!(message.role, rocode_session::MessageRole::User) {
            continue;
        }
        for part in message.parts.iter().rev() {
            if let rocode_session::PartType::Subtask {
                id,
                description,
                status,
            } = &part.part_type
            {
                targets.push(SubtaskRecoveryTarget {
                    checkpoint: RecoveryCheckpointInfo {
                        id: id.clone(),
                        kind: "subtask".to_string(),
                        label: if description.trim().is_empty() {
                            format!("Subtask {id}")
                        } else {
                            description.clone()
                        },
                        status: status.clone(),
                        summary: Some(format!("Subtask is currently `{status}`.")),
                        scheduler_profile: None,
                        stage: None,
                        stage_index: None,
                        stage_total: None,
                    },
                    description: description.clone(),
                });
            }
        }
        if !targets.is_empty() {
            break;
        }
    }
    targets
}

// ---------------------------------------------------------------------------
// Active stage checkpoint from topology
// ---------------------------------------------------------------------------

pub(crate) fn find_active_scheduler_stage_checkpoint(
    topology: &SessionExecutionTopology,
) -> Option<RecoveryCheckpointInfo> {
    let mut best: Option<&SessionExecutionNode> = None;
    fn visit<'a>(node: &'a SessionExecutionNode, best: &mut Option<&'a SessionExecutionNode>) {
        if matches!(node.kind, ExecutionKind::SchedulerStage)
            && matches!(
                node.status,
                ExecutionStatus::Running
                    | ExecutionStatus::Waiting
                    | ExecutionStatus::Cancelling
                    | ExecutionStatus::Retry
            )
        {
            let replace = match best {
                Some(current) => node.updated_at > current.updated_at,
                None => true,
            };
            if replace {
                *best = Some(node);
            }
        }
        for child in &node.children {
            visit(child, best);
        }
    }
    for root in &topology.roots {
        visit(root, &mut best);
    }
    best.map(|node| {
        #[derive(Debug, Default, serde::Deserialize)]
        struct StageNodeMetadataWire {
            #[serde(
                default,
                deserialize_with = "rocode_types::deserialize_opt_string_lossy"
            )]
            scheduler_profile: Option<String>,
            #[serde(
                default,
                deserialize_with = "rocode_types::deserialize_opt_string_lossy"
            )]
            scheduler_stage: Option<String>,
            #[serde(
                default,
                deserialize_with = "rocode_types::deserialize_opt_u64_lossy"
            )]
            scheduler_stage_index: Option<u64>,
            #[serde(
                default,
                deserialize_with = "rocode_types::deserialize_opt_u64_lossy"
            )]
            scheduler_stage_total: Option<u64>,
        }

        let meta: StageNodeMetadataWire = node
            .metadata
            .as_ref()
            .map(rocode_types::parse_value_lossy)
            .unwrap_or_default();

        RecoveryCheckpointInfo {
        id: node.id.clone(),
        kind: "stage".to_string(),
        label: node.label.clone().unwrap_or_else(|| node.id.clone()),
        status: match node.status {
            ExecutionStatus::Running => "running",
            ExecutionStatus::Waiting => "waiting",
            ExecutionStatus::Cancelling => "cancelling",
            ExecutionStatus::Retry => "retry",
            ExecutionStatus::Done => "done",
        }
        .to_string(),
        summary: node.recent_event.clone(),
        scheduler_profile: meta.scheduler_profile,
        stage: meta.scheduler_stage,
        stage_index: meta.scheduler_stage_index.map(|value| value as u32),
        stage_total: meta.scheduler_stage_total.map(|value| value as u32),
        }
    })
}

// ---------------------------------------------------------------------------
// Protocol assembly
// ---------------------------------------------------------------------------

/// Check whether `protocol` currently advertises the given action + target.
pub(crate) fn protocol_allows_recovery_action(
    protocol: &SessionRecoveryProtocol,
    action: &RecoveryActionKind,
    target_id: Option<&str>,
) -> bool {
    protocol.actions.iter().any(|candidate| {
        if &candidate.kind != action {
            return false;
        }
        match (&candidate.target_id, target_id) {
            (Some(expected), Some(actual)) => expected == actual,
            (Some(_), None) => false,
            (None, Some(_)) => false,
            (None, None) => true,
        }
    })
}

/// Build the full recovery protocol snapshot for a session.
pub(crate) fn build_session_recovery_protocol(
    session_id: &str,
    session: &rocode_session::Session,
    topology: &SessionExecutionTopology,
    pending_question_count: usize,
) -> SessionRecoveryProtocol {
    let last_user_prompt = latest_user_prompt(session);
    let stage_targets = collect_stage_recovery_targets(session);
    let subtask_targets = collect_subtask_recovery_targets(session);
    let finish = latest_assistant_finish(session);
    let mut actions = Vec::new();
    let mut checkpoints = Vec::new();

    checkpoints.extend(stage_targets.iter().map(|target| target.checkpoint.clone()));
    checkpoints.extend(
        subtask_targets
            .iter()
            .map(|target| target.checkpoint.clone()),
    );

    let busy = topology.active_count > 0;
    if busy || pending_question_count > 0 {
        actions.push(RecoveryActionInfo {
            kind: RecoveryActionKind::AbortRun,
            label: "Abort run".to_string(),
            description: "Stop the current session run and return control to recovery mode."
                .to_string(),
            target_id: None,
            target_kind: None,
        });
        if let Some(stage) = find_active_scheduler_stage_checkpoint(topology) {
            actions.push(RecoveryActionInfo {
                kind: RecoveryActionKind::AbortStage,
                label: format!("Abort stage · {}", stage.label),
                description:
                    "Cancel only the current scheduler stage and keep the wider session available for recovery."
                        .to_string(),
                target_id: Some(stage.id),
                target_kind: Some("stage".to_string()),
            });
        }
    }

    if !busy && pending_question_count == 0 {
        if last_user_prompt.is_some() && matches!(finish.as_deref(), Some("error" | "cancelled")) {
            actions.push(RecoveryActionInfo {
                kind: RecoveryActionKind::Retry,
                label: "Retry last run".to_string(),
                description: "Re-run the last request with the same agent or preset configuration."
                    .to_string(),
                target_id: None,
                target_kind: None,
            });
        }
        if last_user_prompt.is_some() {
            actions.push(RecoveryActionInfo {
                kind: RecoveryActionKind::Resume,
                label: "Resume from latest boundary".to_string(),
                description:
                    "Continue from the most recent incomplete boundary without re-discovering the whole task."
                        .to_string(),
                target_id: None,
                target_kind: None,
            });
        }
        if let Some(stage) = stage_targets
            .iter()
            .find(|target| target.checkpoint.status != "done")
            .or_else(|| stage_targets.first())
        {
            actions.push(RecoveryActionInfo {
                kind: RecoveryActionKind::RestartStage,
                label: format!("Restart stage · {}", stage.checkpoint.label),
                description:
                    "Restart from this scheduler stage and replay only the necessary downstream work."
                        .to_string(),
                target_id: Some(stage.checkpoint.id.clone()),
                target_kind: Some("stage".to_string()),
            });
            actions.push(RecoveryActionInfo {
                kind: RecoveryActionKind::PartialReplay,
                label: format!("Partial replay · {}", stage.checkpoint.label),
                description:
                    "Replay from this stage boundary while preserving already valid prior work."
                        .to_string(),
                target_id: Some(stage.checkpoint.id.clone()),
                target_kind: Some("stage".to_string()),
            });
        }
        if let Some(subtask) = subtask_targets
            .iter()
            .find(|target| target.checkpoint.status != "completed")
            .or_else(|| subtask_targets.first())
        {
            actions.push(RecoveryActionInfo {
                kind: RecoveryActionKind::RestartSubtask,
                label: format!("Restart subtask · {}", subtask.checkpoint.label),
                description:
                    "Restart just this subtask boundary and keep other completed work intact."
                        .to_string(),
                target_id: Some(subtask.checkpoint.id.clone()),
                target_kind: Some("subtask".to_string()),
            });
        }
    }

    let (status, summary) = if busy {
        (
            RecoveryProtocolStatus::Running,
            Some(format!(
                "{} active execution(s) are still running; recovery actions unlock after the current run stops.",
                topology.active_count
            )),
        )
    } else if pending_question_count > 0 {
        (
            RecoveryProtocolStatus::AwaitingUser,
            Some(format!(
                "{} pending question(s) need answers before recovery can continue.",
                pending_question_count
            )),
        )
    } else if !actions.is_empty() {
        (
            RecoveryProtocolStatus::Recoverable,
            Some(
                "Recovery actions are available at run, stage, and subtask granularity."
                    .to_string(),
            ),
        )
    } else {
        (
            RecoveryProtocolStatus::Idle,
            Some("No active recovery target was inferred for this session.".to_string()),
        )
    };

    SessionRecoveryProtocol {
        session_id: session_id.to_string(),
        status,
        active_execution_count: topology.active_count,
        pending_question_count,
        summary,
        last_user_prompt,
        actions,
        checkpoints,
    }
}

// ---------------------------------------------------------------------------
// Prompt composition
// ---------------------------------------------------------------------------

pub(crate) fn compose_retry_prompt(base_prompt: &str) -> String {
    format!(
        "Recovery protocol: retry the previous request with the same mode and constraints.\nPreserve any valid prior work, but re-run the task end-to-end where needed.\n\nOriginal request:\n{base_prompt}"
    )
}

pub(crate) fn compose_resume_prompt(base_prompt: &str) -> String {
    format!(
        "Recovery protocol: resume from the latest incomplete boundary.\nDo not restart discovery from scratch. Preserve prior verified work, artifacts, decisions, and constraints.\n\nOriginal request:\n{base_prompt}"
    )
}

pub(crate) fn compose_restart_stage_prompt(
    base_prompt: &str,
    target: &StageRecoveryTarget,
) -> String {
    let stage_name = target
        .checkpoint
        .stage
        .as_deref()
        .unwrap_or(target.checkpoint.label.as_str());
    let profile = target
        .checkpoint
        .scheduler_profile
        .as_deref()
        .unwrap_or("scheduler");
    let stage_ref = match (target.checkpoint.stage_index, target.checkpoint.stage_total) {
        (Some(index), Some(total)) => format!("{stage_name} ({index}/{total})"),
        _ => stage_name.to_string(),
    };
    let detail = short_recovery_text(&target.body, 1200)
        .unwrap_or_else(|| "No prior stage output available.".to_string());
    format!(
        "Recovery protocol: restart scheduler stage `{stage_ref}` in preset `{profile}`.\nRe-enter this stage as a fresh boundary. Preserve global constraints and prior validated upstream context, but allow this stage and all downstream work to be recomputed from here.\n\nPrevious stage outcome:\n{detail}\n\nOriginal request:\n{base_prompt}"
    )
}

pub(crate) fn compose_stage_recovery_prompt(
    base_prompt: &str,
    target: &StageRecoveryTarget,
) -> String {
    let stage_name = target
        .checkpoint
        .stage
        .as_deref()
        .unwrap_or(target.checkpoint.label.as_str());
    let profile = target
        .checkpoint
        .scheduler_profile
        .as_deref()
        .unwrap_or("scheduler");
    let stage_ref = match (target.checkpoint.stage_index, target.checkpoint.stage_total) {
        (Some(index), Some(total)) => format!("{stage_name} ({index}/{total})"),
        _ => stage_name.to_string(),
    };
    let summary = target
        .checkpoint
        .summary
        .as_deref()
        .unwrap_or("No prior stage summary available.");
    let detail = short_recovery_text(&target.body, 1200).unwrap_or_else(|| summary.to_string());
    format!(
        "Recovery protocol: partial replay from scheduler stage `{stage_ref}` in preset `{profile}`.\nRestart from this stage boundary only. Preserve all prior valid work and replay only the downstream work required after this stage.\n\nPrevious stage outcome:\n{detail}\n\nOriginal request:\n{base_prompt}"
    )
}

pub(crate) fn compose_subtask_recovery_prompt(
    base_prompt: &str,
    target: &SubtaskRecoveryTarget,
) -> String {
    let label = if target.description.trim().is_empty() {
        target.checkpoint.label.clone()
    } else {
        target.description.clone()
    };
    format!(
        "Recovery protocol: restart subtask `{label}`.\nReplay only this subtask boundary and the minimum downstream integration work. Preserve all other completed work and constraints.\n\nOriginal request:\n{base_prompt}"
    )
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime_control::SessionExecutionTopology;

    #[test]
    fn short_recovery_text_truncates_at_limit() {
        assert_eq!(
            short_recovery_text("hello world", 5),
            Some("hello…".to_string())
        );
        assert_eq!(short_recovery_text("short", 100), Some("short".to_string()));
        assert_eq!(short_recovery_text("   ", 10), None);
        assert_eq!(short_recovery_text("", 10), None);
    }

    #[test]
    fn recovery_protocol_surfaces_run_stage_and_subtask_actions() {
        let mut session = rocode_session::Session::new("default", ".");
        session
            .metadata
            .insert("scheduler_profile".to_string(), serde_json::json!("atlas"));
        session
            .metadata
            .insert("model_provider".to_string(), serde_json::json!("openai"));
        session
            .metadata
            .insert("model_id".to_string(), serde_json::json!("gpt-5"));

        let user = session.add_user_message("Refactor the scheduler runtime");
        user.add_subtask("sub_1", "Verify stage recovery");
        let assistant = session.add_assistant_message();
        assistant.finish = Some("error".to_string());
        assistant.metadata.insert(
            "scheduler_stage".to_string(),
            serde_json::json!("coordination-gate"),
        );
        assistant.metadata.insert(
            "scheduler_stage_status".to_string(),
            serde_json::json!("blocked"),
        );
        assistant
            .metadata
            .insert("scheduler_stage_index".to_string(), serde_json::json!(3));
        assistant
            .metadata
            .insert("scheduler_stage_total".to_string(), serde_json::json!(5));
        assistant.metadata.insert(
            "resolved_scheduler_profile".to_string(),
            serde_json::json!("atlas"),
        );
        assistant
            .add_text("{\"status\":\"blocked\",\"summary\":\"Task B still lacks verification.\"}");

        let protocol = build_session_recovery_protocol(
            &session.id,
            &session,
            &SessionExecutionTopology {
                session_id: session.id.clone(),
                active_count: 0,
                done_count: 0,
                running_count: 0,
                waiting_count: 0,
                cancelling_count: 0,
                retry_count: 0,
                updated_at: None,
                roots: Vec::new(),
            },
            0,
        );

        assert_eq!(protocol.status, RecoveryProtocolStatus::Recoverable);
        assert!(protocol
            .actions
            .iter()
            .any(|action| action.kind == RecoveryActionKind::Retry));
        assert!(protocol
            .actions
            .iter()
            .any(|action| action.kind == RecoveryActionKind::RestartStage));
        assert!(protocol
            .actions
            .iter()
            .any(|action| action.kind == RecoveryActionKind::RestartSubtask));
        assert!(protocol
            .checkpoints
            .iter()
            .any(|checkpoint| checkpoint.kind == "stage"));
        assert!(protocol
            .checkpoints
            .iter()
            .any(|checkpoint| checkpoint.kind == "subtask"));
    }

    #[test]
    fn stage_recovery_prompt_preserves_boundary_language() {
        let target = StageRecoveryTarget {
            checkpoint: RecoveryCheckpointInfo {
                id: "msg_1".to_string(),
                kind: "stage".to_string(),
                label: "Coordination Gate".to_string(),
                status: "blocked".to_string(),
                summary: Some("Task B still lacks verification.".to_string()),
                scheduler_profile: Some("atlas".to_string()),
                stage: Some("coordination-gate".to_string()),
                stage_index: Some(3),
                stage_total: Some(5),
            },
            body: "{\"status\":\"blocked\",\"summary\":\"Task B still lacks verification.\"}"
                .to_string(),
        };

        let prompt = compose_stage_recovery_prompt("Fix the scheduler", &target);
        assert!(prompt.contains("partial replay"));
        assert!(prompt.contains("coordination-gate (3/5)"));
        assert!(prompt.contains("Preserve all prior valid work"));
    }

    #[test]
    fn restart_stage_prompt_uses_fresh_boundary_language() {
        let target = StageRecoveryTarget {
            checkpoint: RecoveryCheckpointInfo {
                id: "msg_1".to_string(),
                kind: "stage".to_string(),
                label: "Coordination Gate".to_string(),
                status: "blocked".to_string(),
                summary: Some("Task B still lacks verification.".to_string()),
                scheduler_profile: Some("atlas".to_string()),
                stage: Some("coordination-gate".to_string()),
                stage_index: Some(3),
                stage_total: Some(5),
            },
            body: "{\"status\":\"blocked\",\"summary\":\"Task B still lacks verification.\"}"
                .to_string(),
        };

        let prompt = compose_restart_stage_prompt("Fix the scheduler", &target);
        assert!(prompt.contains("restart scheduler stage"));
        assert!(prompt.contains("fresh boundary"));
        assert!(prompt.contains("recomputed from here"));
    }

    #[test]
    fn recovery_protocol_surfaces_abort_actions_while_running() {
        let session = rocode_session::Session::new("proj", "/tmp");
        let topology = SessionExecutionTopology {
            session_id: session.id.clone(),
            active_count: 2,
            done_count: 0,
            running_count: 2,
            waiting_count: 0,
            cancelling_count: 0,
            retry_count: 0,
            updated_at: Some(10),
            roots: vec![SessionExecutionNode {
                id: format!("prompt:{}", session.id),
                kind: ExecutionKind::PromptRun,
                status: ExecutionStatus::Running,
                label: Some("Prompt run".to_string()),
                parent_id: None,
                stage_id: None,
                waiting_on: None,
                recent_event: Some("Prompt run started".to_string()),
                started_at: 1,
                updated_at: 1,
                metadata: None,
                children: vec![SessionExecutionNode {
                    id: "msg_stage_active".to_string(),
                    kind: ExecutionKind::SchedulerStage,
                    status: ExecutionStatus::Running,
                    label: Some("Coordination Gate".to_string()),
                    parent_id: Some(format!("prompt:{}", session.id)),
                    stage_id: Some("msg_stage_active".to_string()),
                    waiting_on: Some("model".to_string()),
                    recent_event: Some("Evaluating route".to_string()),
                    started_at: 2,
                    updated_at: 9,
                    metadata: Some(serde_json::json!({
                        "scheduler_profile": "atlas",
                        "scheduler_stage": "coordination-gate",
                        "scheduler_stage_index": 2,
                        "scheduler_stage_total": 5
                    })),
                    children: Vec::new(),
                }],
            }],
        };

        let protocol = build_session_recovery_protocol(&session.id, &session, &topology, 0);
        assert_eq!(protocol.status, RecoveryProtocolStatus::Running);
        assert!(protocol
            .actions
            .iter()
            .any(|action| action.kind == RecoveryActionKind::AbortRun));
        assert!(protocol
            .actions
            .iter()
            .any(|action| action.kind == RecoveryActionKind::AbortStage));
    }

    #[test]
    fn protocol_only_allows_actions_advertised_by_current_state() {
        let protocol = SessionRecoveryProtocol {
            session_id: "ses_1".to_string(),
            status: RecoveryProtocolStatus::Recoverable,
            active_execution_count: 0,
            pending_question_count: 0,
            summary: None,
            last_user_prompt: Some("Fix it".to_string()),
            actions: vec![RecoveryActionInfo {
                kind: RecoveryActionKind::RestartStage,
                label: "Restart stage · Plan".to_string(),
                description: "restart".to_string(),
                target_id: Some("msg_1".to_string()),
                target_kind: Some("stage".to_string()),
            }],
            checkpoints: Vec::new(),
        };

        assert!(protocol_allows_recovery_action(
            &protocol,
            &RecoveryActionKind::RestartStage,
            Some("msg_1")
        ));
        assert!(!protocol_allows_recovery_action(
            &protocol,
            &RecoveryActionKind::RestartStage,
            Some("msg_other")
        ));
        assert!(!protocol_allows_recovery_action(
            &protocol,
            &RecoveryActionKind::Retry,
            None
        ));
    }

    #[test]
    fn subtask_recovery_prompt_includes_label() {
        let target = SubtaskRecoveryTarget {
            checkpoint: RecoveryCheckpointInfo {
                id: "sub_1".to_string(),
                kind: "subtask".to_string(),
                label: "Verify stage recovery".to_string(),
                status: "pending".to_string(),
                summary: Some("Subtask is currently `pending`.".to_string()),
                scheduler_profile: None,
                stage: None,
                stage_index: None,
                stage_total: None,
            },
            description: "Verify stage recovery".to_string(),
        };
        let prompt = compose_subtask_recovery_prompt("Do the thing", &target);
        assert!(prompt.contains("Verify stage recovery"));
        assert!(prompt.contains("restart subtask"));
    }
}
