// ── Constants & Initial State ───────────────────────────────────────────────
const THEMES = [
  { id: "midnight", label: "Midnight" },
  { id: "graphite", label: "Graphite" },
  { id: "sunset", label: "Sunset" },
  { id: "daylight", label: "Daylight" },
];

const WIRE_KEYS = {
  TYPE: "type",
  SESSION_ID: "sessionID",
  SESSION_ID_ALIAS: "sessionId",
  MESSAGE_ID: "messageID",
  MESSAGE_ID_ALIAS: "messageId",
  TOOL_CALL_ID: "toolCallId",
  PARENT_ID: "parentID",
  PARENT_ID_ALIAS: "parentId",
  CHILD_ID: "childID",
  CHILD_ID_ALIAS: "childId",
  EXECUTION_ID: "executionID",
  STAGE_ID: "stageID",
  REQUEST_ID: "requestID",
  REQUEST_ID_ALIAS: "requestId",
  PERMISSION_ID: "permissionID",
  PERMISSION_ID_ALIAS: "permissionId",
  ERROR: "error",
  MESSAGE: "message",
  BLOCK: "block",
};

const SERVER_EVENT_TYPES = {
  MESSAGE: "message",
  OUTPUT_BLOCK: "output_block",
  USAGE: "usage",
  ERROR: "error",
  SESSION_UPDATED: "session.updated",
  SESSION_STATUS: "session.status",
  EXECUTION_TOPOLOGY_CHANGED: "execution.topology.changed",
  QUESTION_CREATED: "question.created",
  QUESTION_RESOLVED: "question.resolved",
  QUESTION_REPLIED: "question.replied",
  QUESTION_REJECTED: "question.rejected",
  PERMISSION_REQUESTED: "permission.requested",
  PERMISSION_RESOLVED: "permission.resolved",
  PERMISSION_REPLIED: "permission.replied",
  CONFIG_UPDATED: "config.updated",
  CHILD_SESSION_ATTACHED: "child_session.attached",
  CHILD_SESSION_DETACHED: "child_session.detached",
  TOOL_CALL_LIFECYCLE: "tool_call.lifecycle",
  DIFF_UPDATED: "diff.updated",
};

const OUTPUT_BLOCK_KINDS = {
  STATUS: "status",
  MESSAGE: "message",
  REASONING: "reasoning",
  TOOL: "tool",
  SESSION_EVENT: "session_event",
  QUEUE_ITEM: "queue_item",
  SCHEDULER_STAGE: "scheduler_stage",
  INSPECT: "inspect",
};

const OUTPUT_BLOCK_TONES = {
  NORMAL: "normal",
  WARNING: "warning",
  SUCCESS: "success",
  ERROR: "error",
  MUTED: "muted",
  STATUS: "status",
};

const BADGE_TONES = {
  IDLE: "idle",
  OK: "ok",
  WARN: "warn",
  ERROR: "error",
};

const MESSAGE_ROLES = {
  USER: "user",
  ASSISTANT: "assistant",
  SYSTEM: "system",
  TOOL: "tool",
  REASONING: "reasoning",
};

const MESSAGE_PHASES = {
  START: "start",
  DELTA: "delta",
  END: "end",
  FULL: "full",
};

const MESSAGE_PART_TYPES = {
  TEXT: "text",
  REASONING: "reasoning",
  COMPACTION: "compaction",
  OUTPUT_BLOCK: SERVER_EVENT_TYPES.OUTPUT_BLOCK,
};

const TOOL_PHASES = {
  START: "start",
  RUNNING: "running",
  DONE: "done",
  RESULT: "result",
  ERROR: "error",
};

const QUESTION_STATUSES = {
  PENDING: "pending",
  ANSWERED: "answered",
  REJECTED: "rejected",
  CANCELLED: "cancelled",
  ERROR: "error",
};

const PERMISSION_STATUSES = {
  PENDING: "pending",
  RESOLVED: "resolved",
  REJECTED: "rejected",
};

const PERMISSION_REPLIES = {
  ONCE: "once",
  ALWAYS: "always",
  REJECT: "reject",
};

const INTERACTION_TYPES = {
  QUESTION: "question",
  PERMISSION: "permission",
};

const SCHEDULER_STAGE_STATUSES = {
  WAITING: "waiting",
  RUNNING: "running",
  CANCELLING: "cancelling",
  CANCELLED: "cancelled",
  DONE: "done",
  BLOCKED: "blocked",
  CONTINUE: "continue",
};

const EXECUTION_KINDS = {
  PROMPT_RUN: "prompt_run",
  SCHEDULER_RUN: "scheduler_run",
  SCHEDULER_STAGE: "scheduler_stage",
  TOOL_CALL: "tool_call",
  AGENT_TASK: "agent_task",
  QUESTION: "question",
};

const QUESTION_RESOLUTION_EVENT_TYPES = [
  SERVER_EVENT_TYPES.QUESTION_RESOLVED,
  SERVER_EVENT_TYPES.QUESTION_REPLIED,
  SERVER_EVENT_TYPES.QUESTION_REJECTED,
];

const PERMISSION_RESOLUTION_EVENT_TYPES = [
  SERVER_EVENT_TYPES.PERMISSION_RESOLVED,
  SERVER_EVENT_TYPES.PERMISSION_REPLIED,
];

const state = {
  sessions: [],
  projects: [],
  providers: [],
  modes: [],
  uiCommands: [],
  selectedProject: null,
  selectedSession: null,
  selectedModel: null,
  selectedModeKey: null,
  selectedTheme: "daylight",
  showThinking: true,
  streaming: false,
  abortRequested: false,
  busyAction: null,
  executionTopology: null,
  recoveryProtocol: null,
  executionRefreshTimer: null,
  promptTokens: 0,
  completionTokens: 0,
  streamMessageArticle: null,
  streamMessageNode: null,
  streamReasoningArticle: null,
  streamReasoningNode: null,
  streamReasoningText: "",
  streamToolBlocks: new Map(),
  streamEventBlocks: new Map(),
  streamStageBlocks: new Map(),
  focusedChildSessionId: null,
  childSessionLiveBlocks: new Map(),
  activeQuestionInteraction: null,
  questionSubmitting: false,
  activePermissionInteraction: null,
  permissionSubmitting: false,
  parentSessionId: null,
  settingsActiveTab: "general",
  configSnapshot: null,
  knownProviders: [],
  settingsProviderSelection: null,
  settingsModelSelection: null,
  schedulerConfigSnapshot: null,
  settingsMcpSelection: null,
  settingsPluginSelection: null,
  settingsInlineActions: {
    provider: null,
    model: null,
    mcp: null,
    plugin: null,
  },
  mcpStatusSnapshot: {},
  pluginAuthSnapshot: [],
  lspStatusSnapshot: { servers: [] },
  formatterStatusSnapshot: { formatters: [] },
  terminalOpen: false,
  terminalSessions: [],
  terminalActiveId: null,
  terminalBuffers: new Map(),
  terminalSockets: new Map(),
  terminalCursorById: new Map(),
};

const nodes = {
  shell: document.getElementById("appShell"),
  sidebarToggle: document.getElementById("sidebarToggle"),
  projectSearch: document.getElementById("projectSearch"),
  projectCount: document.getElementById("projectCount"),
  projectTree: document.getElementById("projectTree"),
  heroPanel: document.getElementById("heroPanel"),
  conversationPanel: document.getElementById("conversationPanel"),
  sessionTitle: document.getElementById("sessionTitle"),
  sessionRuntimeMeta: document.getElementById("sessionRuntimeMeta"),
  sessionMeta: document.getElementById("sessionMeta"),
  executionPanel: document.getElementById("executionPanel"),
  recoveryPanel: document.getElementById("recoveryPanel"),
  stageInspectorPanel: document.getElementById("stageInspectorPanel"),
  childSessionRail: document.getElementById("childSessionRail"),
  focusedChildPanel: document.getElementById("focusedChildPanel"),
  messageFeed: document.getElementById("messageFeed"),
  workspacePanel: document.getElementById("workspacePanel"),
  terminalPanel: document.getElementById("terminalPanel"),
  terminalToggleBtn: document.getElementById("terminalToggleBtn"),
  workspaceToggleBtn: document.getElementById("workspaceToggleBtn"),
  terminalTabList: document.getElementById("terminalTabList"),
  terminalViewport: document.getElementById("terminalViewport"),
  terminalNewBtn: document.getElementById("terminalNewBtn"),
  terminalCollapseBtn: document.getElementById("terminalCollapseBtn"),
  terminalInputForm: document.getElementById("terminalInputForm"),
  terminalInput: document.getElementById("terminalInput"),
  refreshSession: document.getElementById("refreshSession"),
  newSessionBtn: document.getElementById("newSessionBtn"),
  heroNewSessionBtn: document.getElementById("heroNewSessionBtn"),
  forkSessionBtn: document.getElementById("forkSessionBtn"),
  compactSessionBtn: document.getElementById("compactSessionBtn"),
  renameSessionBtn: document.getElementById("renameSessionBtn"),
  shareSessionBtn: document.getElementById("shareSessionBtn"),
  deleteSessionBtn: document.getElementById("deleteSessionBtn"),
  commandBtn: document.getElementById("commandBtn"),
  commandPanel: document.getElementById("commandPanel"),
  commandClose: document.getElementById("commandClose"),
  commandAbortBtn: document.getElementById("commandAbortBtn"),
  commandRuntimeBadge: document.getElementById("commandRuntimeBadge"),
  commandRuntimeText: document.getElementById("commandRuntimeText"),
  settingsTabList: document.getElementById("settingsTabList"),
  settingsGeneralPanel: document.getElementById("settingsGeneralPanel"),
  settingsProvidersPanel: document.getElementById("settingsProvidersPanel"),
  settingsSchedulerPanel: document.getElementById("settingsSchedulerPanel"),
  settingsMcpPanel: document.getElementById("settingsMcpPanel"),
  settingsPluginsPanel: document.getElementById("settingsPluginsPanel"),
  settingsLspPanel: document.getElementById("settingsLspPanel"),
  settingsCommandsPanel: document.getElementById("settingsCommandsPanel"),
  settingsSessionsPanel: document.getElementById("settingsSessionsPanel"),
  modelSelect: document.getElementById("modelSelect"),
  themeSelect: document.getElementById("themeSelect"),
  agentSelect: document.getElementById("agentSelect"),
  settingsProviderReloadBtn: document.getElementById("settingsProviderReloadBtn"),
  settingsProviderNewBtn: document.getElementById("settingsProviderNewBtn"),
  settingsProviderList: document.getElementById("settingsProviderList"),
  settingsKnownProviderList: document.getElementById("settingsKnownProviderList"),
  settingsProviderEmptyState: document.getElementById("settingsProviderEmptyState"),
  settingsProviderEditor: document.getElementById("settingsProviderEditor"),
  settingsProviderKey: document.getElementById("settingsProviderKey"),
  settingsProviderId: document.getElementById("settingsProviderId"),
  settingsProviderName: document.getElementById("settingsProviderName"),
  settingsProviderBaseUrl: document.getElementById("settingsProviderBaseUrl"),
  settingsProviderApiKey: document.getElementById("settingsProviderApiKey"),
  settingsProviderEnv: document.getElementById("settingsProviderEnv"),
  settingsProviderOptions: document.getElementById("settingsProviderOptions"),
  settingsModelNewBtn: document.getElementById("settingsModelNewBtn"),
  settingsModelRenameBtn: document.getElementById("settingsModelRenameBtn"),
  settingsModelDeleteBtn: document.getElementById("settingsModelDeleteBtn"),
  settingsModelList: document.getElementById("settingsModelList"),
  settingsModelInlineAction: document.getElementById("settingsModelInlineAction"),
  settingsModelEmptyState: document.getElementById("settingsModelEmptyState"),
  settingsModelEditor: document.getElementById("settingsModelEditor"),
  settingsModelKey: document.getElementById("settingsModelKey"),
  settingsModelRuntimeId: document.getElementById("settingsModelRuntimeId"),
  settingsModelName: document.getElementById("settingsModelName"),
  settingsModelFamily: document.getElementById("settingsModelFamily"),
  settingsModelReasoning: document.getElementById("settingsModelReasoning"),
  settingsModelToolCall: document.getElementById("settingsModelToolCall"),
  settingsModelTemperature: document.getElementById("settingsModelTemperature"),
  settingsModelAttachment: document.getElementById("settingsModelAttachment"),
  settingsModelHeaders: document.getElementById("settingsModelHeaders"),
  settingsModelOptions: document.getElementById("settingsModelOptions"),
  settingsModelVariants: document.getElementById("settingsModelVariants"),
  settingsProviderStatus: document.getElementById("settingsProviderStatus"),
  settingsProviderInlineAction: document.getElementById("settingsProviderInlineAction"),
  settingsProviderRenameBtn: document.getElementById("settingsProviderRenameBtn"),
  settingsProviderDeleteBtn: document.getElementById("settingsProviderDeleteBtn"),
  settingsProviderSaveBtn: document.getElementById("settingsProviderSaveBtn"),
  settingsSchedulerReloadBtn: document.getElementById("settingsSchedulerReloadBtn"),
  settingsSchedulerTemplateBtn: document.getElementById("settingsSchedulerTemplateBtn"),
  settingsSchedulerSaveBtn: document.getElementById("settingsSchedulerSaveBtn"),
  settingsSchedulerPath: document.getElementById("settingsSchedulerPath"),
  settingsSchedulerMeta: document.getElementById("settingsSchedulerMeta"),
  settingsSchedulerProfiles: document.getElementById("settingsSchedulerProfiles"),
  settingsSchedulerContent: document.getElementById("settingsSchedulerContent"),
  settingsSchedulerStatus: document.getElementById("settingsSchedulerStatus"),
  settingsMcpReloadBtn: document.getElementById("settingsMcpReloadBtn"),
  settingsMcpNewBtn: document.getElementById("settingsMcpNewBtn"),
  settingsMcpList: document.getElementById("settingsMcpList"),
  settingsMcpEmptyState: document.getElementById("settingsMcpEmptyState"),
  settingsMcpEditor: document.getElementById("settingsMcpEditor"),
  settingsMcpName: document.getElementById("settingsMcpName"),
  settingsMcpType: document.getElementById("settingsMcpType"),
  settingsMcpUrl: document.getElementById("settingsMcpUrl"),
  settingsMcpTimeout: document.getElementById("settingsMcpTimeout"),
  settingsMcpEnabled: document.getElementById("settingsMcpEnabled"),
  settingsMcpCommand: document.getElementById("settingsMcpCommand"),
  settingsMcpEnv: document.getElementById("settingsMcpEnv"),
  settingsMcpOauth: document.getElementById("settingsMcpOauth"),
  settingsMcpStatus: document.getElementById("settingsMcpStatus"),
  settingsMcpInlineAction: document.getElementById("settingsMcpInlineAction"),
  settingsMcpRenameBtn: document.getElementById("settingsMcpRenameBtn"),
  settingsMcpDeleteBtn: document.getElementById("settingsMcpDeleteBtn"),
  settingsMcpConnectBtn: document.getElementById("settingsMcpConnectBtn"),
  settingsMcpRestartBtn: document.getElementById("settingsMcpRestartBtn"),
  settingsMcpSaveBtn: document.getElementById("settingsMcpSaveBtn"),
  settingsPluginReloadBtn: document.getElementById("settingsPluginReloadBtn"),
  settingsPluginNewBtn: document.getElementById("settingsPluginNewBtn"),
  settingsPluginList: document.getElementById("settingsPluginList"),
  settingsPluginAuthList: document.getElementById("settingsPluginAuthList"),
  settingsPluginEmptyState: document.getElementById("settingsPluginEmptyState"),
  settingsPluginEditor: document.getElementById("settingsPluginEditor"),
  settingsPluginKey: document.getElementById("settingsPluginKey"),
  settingsPluginType: document.getElementById("settingsPluginType"),
  settingsPluginPackage: document.getElementById("settingsPluginPackage"),
  settingsPluginVersion: document.getElementById("settingsPluginVersion"),
  settingsPluginPath: document.getElementById("settingsPluginPath"),
  settingsPluginRuntime: document.getElementById("settingsPluginRuntime"),
  settingsPluginOptions: document.getElementById("settingsPluginOptions"),
  settingsPluginStatus: document.getElementById("settingsPluginStatus"),
  settingsPluginInlineAction: document.getElementById("settingsPluginInlineAction"),
  settingsPluginRenameBtn: document.getElementById("settingsPluginRenameBtn"),
  settingsPluginDeleteBtn: document.getElementById("settingsPluginDeleteBtn"),
  settingsPluginSaveBtn: document.getElementById("settingsPluginSaveBtn"),
  settingsLspReloadBtn: document.getElementById("settingsLspReloadBtn"),
  settingsLspSaveBtn: document.getElementById("settingsLspSaveBtn"),
  settingsLspStatusSummary: document.getElementById("settingsLspStatusSummary"),
  settingsLspConfig: document.getElementById("settingsLspConfig"),
  settingsFormatterConfig: document.getElementById("settingsFormatterConfig"),
  settingsLspStatus: document.getElementById("settingsLspStatus"),
  commandSessionNewBtn: document.getElementById("commandSessionNewBtn"),
  commandSessionForkBtn: document.getElementById("commandSessionForkBtn"),
  commandSessionCompactBtn: document.getElementById("commandSessionCompactBtn"),
  commandSessionRenameBtn: document.getElementById("commandSessionRenameBtn"),
  commandSessionShareBtn: document.getElementById("commandSessionShareBtn"),
  commandSessionDeleteBtn: document.getElementById("commandSessionDeleteBtn"),
  commandSessionList: document.getElementById("commandSessionList"),
  commandCatalog: document.getElementById("commandCatalog"),
  questionPanel: document.getElementById("questionPanel"),
  questionPanelTitle: document.getElementById("questionPanelTitle"),
  questionPanelStatus: document.getElementById("questionPanelStatus"),
  questionPanelMeta: document.getElementById("questionPanelMeta"),
  questionClose: document.getElementById("questionClose"),
  questionRejectBtn: document.getElementById("questionRejectBtn"),
  questionForm: document.getElementById("questionForm"),
  questionList: document.getElementById("questionList"),
  questionSubmitBtn: document.getElementById("questionSubmitBtn"),
  permissionPanel: document.getElementById("permissionPanel"),
  permissionPanelTitle: document.getElementById("permissionPanelTitle"),
  permissionPanelStatus: document.getElementById("permissionPanelStatus"),
  permissionPanelMeta: document.getElementById("permissionPanelMeta"),
  permissionClose: document.getElementById("permissionClose"),
  permissionRejectBtn: document.getElementById("permissionRejectBtn"),
  permissionAllowBtn: document.getElementById("permissionAllowBtn"),
  permissionAlwaysBtn: document.getElementById("permissionAlwaysBtn"),
  permissionBody: document.getElementById("permissionBody"),
  composerForm: document.getElementById("composerForm"),
  composerInput: document.getElementById("composerInput"),
  cancelRunBtn: document.getElementById("cancelRunBtn"),
  sendButton: document.getElementById("sendButton"),
  statusBadge: document.getElementById("statusBadge"),
  tokenUsage: document.getElementById("tokenUsage"),
  commandHint: document.getElementById("commandHint"),
  modeBadge: document.getElementById("modeBadge"),
  modelBadge: document.getElementById("modelBadge"),
  directoryBadge: document.getElementById("directoryBadge"),
  heroGreeting: document.getElementById("heroGreeting"),
  chipActions: Array.from(document.querySelectorAll(".hero-chip")),
  overflowToggle: document.getElementById("overflowToggle"),
  overflowMenu: document.getElementById("overflowMenu"),
  settingsToggleBtn: document.getElementById("settingsToggleBtn"),
};
